default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: spree
  password: spree123
  host: localhost

development:
  <<: *default
  database: spree_development

test:
  <<: *default
  database: spree_test
